### ISSUE TITLE
ejabberd

### ISSUE THREAD

**Issue by Thomas301263** [ManuGithubSteam/LinJarK#2]
I need help to setup ejabberd in that way that users can create their own account.
Now only Admin can do it. 
Am using
Ubuntu 16.04
Kernel 4.4.0-64-generic
ejabberd 16.01

It was possible to do that with Ubuntu 14.04 and the ejabberd version from repository.
The version of ejabberd which is now installed is also from repository.

**Comment by ManuGithubSteam** [comment]
Hi

ejabberd has nothing to do with linjark.

Please use the proper github repo if they have one.

Thanks

**Comment by Thomas301263** [comment]
Sorry Manuel
I made a mistake in creating an issue
Viele Grüße
Thomas

Am 03.03.2017 um 11:07 schrieb Manuel:
Hi

ejabberd has nothing to do with linjark.

Please use the proper github repo if they have one.

Thanks

**Comment by ManuGithubSteam** [comment]
No worries :-)
